name: libanime
description: A Dart/Flutter library for anime websites downloading and parsing.
version: 0.1.1

homepage: https://github.com/libanime/libanime/
repository: https://github.com/libanime/libanime/
issue_tracker: https://github.com/libanime/libanime/issues
funding:
 - https://boosty.to/libanime
topics:
  - parse
  - http
  - network
  - anime


environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dio: ^5.3.3
  dio_http2_adapter: ^2.5.0
  faker: ^2.1.0
  graphql: ^5.1.2
  html: ^0.15.4
  pubspec_parse: ^1.2.3
  test: ^1.24.9
  universal_html: ^2.2.4
  xpath_selector_html_parser: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0

