name: libanime
description: A Dart/Flutter library for anime websites downloading and parsing.
version: 0.0.1

homepage: https://github.com/libanime/libanime/
repository: https://github.com/libanime/libanime/
funding:
 - https://boosty.to/libanime

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  dio_http2_adapter: ^2.3.1+1
  flutter:
    sdk: flutter
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_dotenv: ^5.1.0


flutter:
  ## IDK what write here =)
