name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v2.3
        with: 
          version: 3.13.9
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: dart pub publish --force
